// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///         import 'firebase_options.dart';
/// // ..
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDzfOWZl152AVyvwJK8fmQ1A3XRGDv7uc',
    appId: '1:539136254081:web:7cc21c16499151a59fad80',
    messagingSenderId: '539136254081',
    projectId: 'login-dashboard-b3dc7',
    authDomain: 'login-dashboard-b3dc7.firebaseapp.com',
    storageBucket: 'login-dashboard-b3dc7.firebasestorage.app',
    measurementId: 'G-EY2L3Y15CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuoQXPkiM4Tr-g3K_0MEkRC7kNdRXttmU',
    appId: '1:539136254081:android:ab3a8981ce351b519fad80',
    messagingSenderId: '539136254081',
    projectId: 'login-dashboard-b3dc7',
    storageBucket: 'login-dashboard-b3dc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbUGQVHfC27vU3PMoJ0TEhniJ6AT8QJjc',
    appId: '1:539136254081:ios:8b37318f3a42783e9fad80',
    messagingSenderId: '539136254081',
    projectId: 'login-dashboard-b3dc7',
    storageBucket: 'login-dashboard-b3dc7.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbUGQVHfC27vU3PMoJ0TEhniJ6AT8QJjc',
    appId: '1:539136254081:ios:8b37318f3a42783e9fad80',
    messagingSenderId: '539136254081',
    projectId: 'login-dashboard-b3dc7',
    storageBucket: 'login-dashboard-b3dc7.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDzfOWZl152AVyvwJK8fmQ1A3XRGDv7uc',
    appId: '1:539136254081:web:3508d70ab95e81779fad80',
    messagingSenderId: '539136254081',
    projectId: 'login-dashboard-b3dc7',
    authDomain: 'login-dashboard-b3dc7.firebaseapp.com',
    storageBucket: 'login-dashboard-b3dc7.firebasestorage.app',
    measurementId: 'G-XNHQKE9DJF',
  );
}
